project:
    name: etl-flows

services:
    webserver:
        command: webserver
        ports:
            - "8080:8080"

        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            - ./plugins:/usr/local/airflow/plugins
        
    scheduler:
        command: scheduler

        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            - ./plugins:/usr/local/airflow/plugins

    fastapi:
        image: python:3.11
        command: uvicorn fastapi_backend.main:app --host 0.0.0.0 --port 8000
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./fastapi_backend:/app/fastapi_backend
        working_dir: /app
        ports:
            - "8000:8000"
